language: go
go:
 - 1.12

sudo: false
branches:
  only:
  - master
before_install:
- ./look_for_logs.sh
- go get github.com/axw/gocov/gocov
- go get github.com/mattn/goveralls
- go get golang.org/x/lint/golint
- go get github.com/GeertJohan/fgt
- if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover;
  fi
script:
- fgt golint $(find . | grep .go$ | grep -v beer.pb.go)
- $HOME/gopath/bin/goveralls -service=travis-ci -ignore=beerserver.go -package github.com/brotherlogic/beerserver
env:
  global:
  - secure: OnKbz575AJPmjw3/p/m5D9P5TDXrbyKzC1WwOMjVxB6yzyCwnAN/aIJw0nf4Grbje8pq/ifuVYkN2kNo6r375ikGG7q+Av2fxE7+8sSRGrU18VPimkSWajMjVzhzhDW22N0pav9mtJxrgi/PHIMgZLU3HiQDH+2ipx85nCErwoEc2AQGfHa0Ib+TYNgTVdw4RjG0rWdBGAEl8Q4TuA/PFMQhL9fWIw1WVPKALwQ6relhsoZyFwmnzrtnCbN6jEW+OlbpD+MImEe5Hxi27vWeUeXONwrIv+O8yvmDEyz0WjttMWLUMhzK12xp30QZHqT0CNYczFG0ClxYQ6E+ZhnBuczCP0RfNFzE8ksJR7y5o3+IPbnFjDU96fYNwvXwRdTnQ+bTzPIL4WvWgcWh10wYThIeAJZ40wDw9dZcbuf7qECGNW/3d0VtZUyWN14akJWBcWozKqbe19pOh6VmRhGoB8GaLVjD3dvV/XXoQGmdE2Uk9eOo9pTgXMTPzMLRsDWEmyCiu9QU4Bp/l5RvyS5OW1B02IIi3u+p5IIhNXT5wWv+faIGgkFCW2nZs4z/FtqX9L1V9TV/6/WzUgtfcUKaAkoZUEo+KrN9P7UAlN1ieKtydOQeysToTcEE0iTY586aHrl/rjszcOg6TeOFmrBJ8rcj5iansg/WklRu15U2RSc=
  - secure: Kd0TK7icRxHltO/cH9ygOgp43wXDoQTNaniGJGbjgqrVehcGdLi/2lUaFaWnk1RAa111+J/JuhIW6MRFeEnFdFa0eaX2V5RzSJeMEZjdCe+obV9HjklxEFKFQ0DB8NdVHKnMjZgDk12/JbAWHa9E09PRWhj5MQdFn3N2x5+a7rdI74c48s+34BIxTtHAUDQZxlLCQeNl/11XDVQX0XiIFyIEdZmgO+9jwczlZK6zvTZ35QHHdgVtZ3V6BGhGoro7Rws20CURvDQ7GK6SkAyo/h/dQxvbPMna7DZZ4cnuJ/J3y+5ID+rEPmvx7osCbzuDmrvFV/tIaZwZuaUIB2iXAgl7EW6HofS6rm0mREGfRXq1P3fFBHH+Ox3FG4Qp9SpsPcXOEmkN3RsJlTYHuUclYsmH6jT/wOMTd40qlfTUqaySq+k0av/Yt1STJEoRdqoQwCnvn8JT4kjdbPi8GETcKzTQnb2l6WmU483nWNjqN2yFVFlB9572fryyatGJqrxQAHlg4MwSqJ3+YV3o+rVaYYcjHWC6kLtZYG7birLhY0k6ZEAMlTHR046607TGirR3OohiZqHS2CdS4SB5bBSuuADnM6DadKDnbH5FDfqgcGy+BaxdQk18S8O64vHtr/XrwCfC06tBcUsUklKnR9qQhh5PlJjzz7lnnOFmkRyVW/Y=
